version: "3.9"
services:
  app:
    build: .
    privileged: true
    environment:
      DISPLAY: "unix$DISPLAY"
    ports:
    - "22:22"
    user: "1000:1000"
    volumes:
      - ./:/opt/project
      - ./docker/cache/:/root/.cache/
      - ./docker/output/:/output/
      - /tmp/.X11-unix:/tmp/.X11-unix
